name: cinebot
description: "A new Flutter project."
publish_to: 'none' 

#App version
version: 1.0.0+1

environment:
  sdk: ^3.8.1

#Dependencies
dependencies:
  flutter:
    sdk: flutter

  markdown_widget: ^2.3.2+8
  flutter_dotenv: ^6.0.0


#iOS style icons
  cupertino_icons: ^1.0.8

#For using lottie animations
  lottie: ^3.3.1

# For Hive Database
  # hive: ^4.0.0-dev.13
  # isar_flutter_libs: ^4.0.0-dev.13

  # Using this version due to less apk size
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # For Accessing Storage Path
  path_provider: ^2.1.3

  # For State Management
  get: ^4.7.2

  # For API Call
  http: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

#Good practices lints
  flutter_lints: ^6.0.0


#For generating app icons
  # icons_launcher: ^3.0.2


flutter:

#Enable Material Design
  uses-material-design: true

  #To add assets to your application, add an assets section, like this:
  assets:
#    - .env
    - assets/images/
    - assets/lottie/
  #fonts:
  #      -family: Schyler
  #       fonts:
  #        - asset: fonts/Schyler-Regular.ttf
  #        - asset: fonts/Schyler-Italic.ttf
  #          style: italic
  #      - family: Trajan Pro
  #        fonts:
  #         - asset: fonts/TrajanPro.ttf
  #         - asset: fonts/TrajanPro_Bold.ttf
  #           weight: 700
  
